#!/bin/sh

# Implement your script here.
if ! git pull origin develop && ! git merge develop --no-commit && ! mvn test; then
  exit 1
fi
# To terminate the git-flow action, return a non-zero exit code.
exit 0
